apiVersion: cis.f5.com/v1
kind: IngressLink
metadata:
  annotations:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  bigipRouteDomain: 0
  host: cafe.example.com
  iRules:
  - /Common/Proxy_Protocol_iRule
  selector:
    matchLabels:
      app: ingresslink
  virtualServerAddress: 10.1.10.101
